version: "3.8"

services:
  # Front-end service (client) container configuration
  client:
    container_name: client
    build: ./front-end
    restart: always
    networks:
      - client-server
    ports:
      - 5173:5173
    volumes:
      - ./front-end:/app
    env_file:
      - ./front-end/.env
    depends_on:
      - server
    command: npm run dev

  # Back-end service (server) container configuration
  server:
    container_name: server
    build: ./back-end
    restart: always
    networks:
      client-server:
        ipv4_address: 172.28.0.5
      server-mongo:
      server-redis:
    ports:
      - 3000:3000
    volumes:
      - ./back-end:/app
    environment:
      - NODE_ENV=dev
    env_file:
      - ./back-end/.env
    depends_on:
      - initReplica
      - redis
    command: sh -c "./entryPoint.sh"

  # Redis service container configuration
  redis:
    container_name: redis
    image: redis:alpine
    restart: always
    networks:
      server-redis:
        ipv4_address: 172.30.0.5
    volumes:
      - redisdb:/data

  # MongoDB service container configuration
  mongoDB1:
    container_name: mongoDB1
    image: mongo:4.4.28
    restart: always
    networks:
      server-mongo:
        ipv4_address: 172.29.0.5
    expose:
      - 27017
    volumes:
      - mongodb1:/data/db
    command: mongod --replSet rs0 --bind_ip_all --port 27017

  # MongoDB service container configuration
  mongoDB2:
    container_name: mongoDB2
    image: mongo:4.4.28
    restart: always
    networks:
      server-mongo:
        ipv4_address: 172.29.0.6
    expose:
      - 27017
    volumes:
      - mongodb2:/data/db
    command: mongod --replSet rs0 --bind_ip_all --port 27017

  initReplica:
    image: mongo:4.4.28
    container_name: initReplica
    depends_on:
      - mongoDB1
      - mongoDB2
    networks:
      server-mongo:
    volumes:
      - ./back-end/databases/initReplica.sh:/initReplica.sh
    entrypoint: ["/bin/bash", "/initReplica.sh"]

# Network configuration
networks:
  # Client-server network configuration
  client-server:
    driver: bridge
    name: client-server
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
  # Server-redis network configuration
  server-redis:
    driver: bridge
    name: server-redis
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/16
  # Server-mongo network configuration
  server-mongo:
    driver: bridge
    name: server-mongo
    ipam:
      driver: default
      config:
        - subnet: 172.29.0.0/16

# Volume configuration
volumes:
  # MongoDB volume configuration
  mongodb1:
    name: mongodb1
  mongodb2:
    name: mongodb2
  # Redis volume configuration
  redisdb:
    name: redisdb
